apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1
  namespace: app1
spec:
  chart:
    spec:
      chart: app1
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: helm-charts
        namespace: flux-system
  values:
    name: app1
