---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app1
  namespace: app1
spec:
  interval: 5m
  releaseName: app1
  chart:
    spec:
      chart: app1
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: helm-charts
        namespace: flux-system
  dependsOn: []